### ISSUE TITLE
Using library with Arduino Zero clone.

### ISSUE THREAD

**Issue by jwmeyer** [JiriBilek/WiFiSpi#10]
I have connected my Wemos D1 mini to the ISP connector on the Zero, SS to D10 and D1 to D7. The SPI never starts on the M0. I added: #include <SPI.h> and SPI.begin(); to the client app and the SPI now connects to the ESP8266 with no issues. Could you point me in the right direction to add this to your library or could you check to see why the SPI isn't starting on the M0.

**Comment by JiriBilek** [comment]
Hi.
could you please add a minimum sketch showing the problem?
Thanks.

**Comment by jwmeyer** [comment]
Sorry, I installed WiFiSpiESP v 0.1.4 and it now works correctly.
