### ISSUE TITLE
Protocol version mismatch. Please upgrade the firmware

### ISSUE THREAD

**Issue by voodoo-business** [JiriBilek/WiFiSpi#31]
Hi there

I hope this is not something that has been addressed elsewhere, but i am facing a little problem using this software

I have downloaded the software for the ESP8266 and the software for the Arduino, it seems that there is a version mismatch, when i go to grab matching versions, I find that even when both are labeled as release 0.2.5,  WiFiSpi contains version 0.2.3 and WiFiSpiESP is at 0.2.4, and I can not seem to find matching versions in both projects (At least not recent ones)

I am presented with the error "Protocol version mismatch. Please upgrade the firmware"

Thank you in advance

**Comment by JiriBilek** [comment]
Please use the lastest github versions, they are synchronized. I am afraid, the releases are out of sync.

**Comment by JiriBilek** [comment]
Hi, I checked the releases and protocol in both releases 0.2.5 match. Nevertheless in Arduino IDE, the recent version of WiFiSPI is 0.2.4 that won't work. 
As I am not familiar with the Arduino library updates, all I can suggest you is to get the release 0.2.5 from this repository, unpack it and overwrite the old version.

**Comment by JAndrassy** [comment]
Jiri, retag 2.5.0 with version 2.5.0 in library.properties

**Comment by JiriBilek** [comment]
Juraj, thanks! With your help, I fixed it.

**Comment by JiriBilek** [comment]
The change is propagated in Arduino IDE now.

**Comment by voodoo-business** [comment]
Thank you jandrassy and Jiri, it works now ! have a blessed day ahead

**Comment by voodoo-business** [comment]
Hello JiriBliek

The same issue appeared again after the 0.3.0 update
Once more, I am presented with the error "Protocol version mismatch. Please upgrade the firmware"

Thank you for all the effort you have put in this project
Kindly Advise

Yours
Yazeed

**Comment by voodoo-business** [comment]
I apologize, My bad, it seems the upload to the Arduino failed, and hence the error which is obviously not an issue with this software
